<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-08 11:21
=======
# Generated by Django 3.2.14 on 2023-03-08 10:22
>>>>>>> 327fb65821c372b143e660390c97edd86c54dd5e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now=True)),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "orders",
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orders',
>>>>>>> 327fb65821c372b143e660390c97edd86c54dd5e
            },
        ),
    ]
