# Generated by Django 4.1.7 on 2023-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now=True)),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
